---
- name: Install prerequisites
  apt:
    name:
      - curl
      - git
    state: present
    update_cache: yes

- name: Install Node.js
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
  args:
    executable: /bin/bash

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Clone GitLab repo
  git:
    repo: "https://gitlab.com/abhaynayar/node-hello.git"
    dest: "/opt/node-hello"
    version: main
    force: yes
    accept_hostkey: yes

- name: Install npm dependencies
  npm:
    path: "/opt/node-hello"

- name: Restart app with PM2
  shell: |
    pm2 delete node-hello || true
    pm2 start index.js --name node-hello
    pm2 save
  args:
    chdir: "/opt/node-hello"
