---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install useful utilities
  apt:
    name:
      - curl
      - git
      - htop
      - unzip
    state: present

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes

