stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.11
  before_script:
    - apt-get update && apt-get install -y openssh-client git
    - pip install ansible
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "[web]" > ansible/inventory.ini
    - echo "$EC2_HOST ansible_user=$EC2_USER ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini
    - ansible-playbook -i ansible/inventory.ini ansible/node_service.yml
  only:
    - main
